---
# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - js
file:
  - ./test/integration.cjs
forbid-only: false
forbid-pending: false
full-trace: false
growl: false
ignore:
  - /path/to/some/ignored/file
inline-diffs: false
opts: false
recursive: false
reporter: spec
require:
  - ./test/setup.cjs
retries: 1
slow: 75
sort: false
spec: lib/**/*.spec.cjs # the positional arguments!
timeout: 0 # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
ui: bdd
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
