---
delimiter: ","
playlist:
  outputPath: default.m3u
  outputDirectory: ".mpd/playlists/"
mpd:
  port: 6600
  host: localhost
  baseDirectory: "/Music/Sorted"
daemon:
  duration: 5000
  bin: "/usr/bin/notify-send"
  urgency: LOW
  icon: false
  fields:
  - artist
  - context
  - mood
rating:
  tag: POPM
  email: Default
  max: 5
output:
  verbosity: 4
  padding: 1
  table:
    headers:
      visible: true
      capitalize: false
    seperators:
      vertical: false
      horizontal: false
  vertical:
    headers:
      visible: true
stats:
  multiFields:
  - context
  - mood
  filters:
  - name: All Songs > 4.0
    filter: rating:4.0
  - name: All Songs > 4.5
    filter: rating:4.5
  - name: All Songs > 5.0
    filter: rating:5.0
  - name: Singles > 4.0
    filter: rating:4.0 type:singles
  - name: Total
    filter: rating:5.0
tags:
- id: TPE1
  name: artist
  tableOrder: 1
- id: TIT2
  name: title
  tableOrder: 2
  maxWidth: 30
- id: TALB
  name: album
  tableOrder: 3
  maxWidth: 20
- id: TCON
  name: genre
library:
  tagId: ID3v2.4
  basePath: "/home/nicholas/Music"
websocket:
  port: 8999
server:
  port: 3000
logger:
  colors:
    fatal:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 230
      - 20
      - 20
    error:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 180
      - 20
      - 20
    warn:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 180
      - 60
      - 20
    log:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 60
      - 110
      - 180
    info:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 20
      - 50
      - 130
    debug:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 80
      - 100
      - 200
    trace:
      fg:
      - 255
      - 255
      - 255
      bg:
      - 100
      - 150
      - 220
  file:
    name: musicman.log
    level: 3
  stdout:
    level: 5
